import Navigation from "@/components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-blue-900 min-h-screen flex">
          <Navigation />
          <div className="bg-white flex-grow mt-2 mx-2 mb-2 rounded-lg p-5">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
